language: node_js

script:     
     - npm install 
     - npm run build
deploy:
  provider: heroku
  api_key:
     secure: KEY
  app: service-forum-back
  on:
    repo: NoSchool2K20/3ServiceForum_Back