language: node_js


script:     
     - npm install 
     - npm run build

deploy:
  provider: heroku
  api_key:
     secure: 663bcfe6-1b58-4453-9679-d50680ceda63
  app: service-forum-back
  on:
    repo: NoSchool2K20/3ServiceForum_Back