language: node_js


script:     
     - npm install 
     - npm run build

deploy:
  provider: heroku
  api_key:
     secure: 6e1bce3b1-64d7-40bf-b2df-2595d5b98fc7
  app: service-forum-back
  on:
    repo: NoSchool2K20/3ServiceForum_Back