version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  deploy:
    executor:
      name: node/default
    steps:
      - checkout      
      - run:
          name: clever deploy
          command: |
            git remote add clever https://$CLEVER_TOKEN:$CLEVER_SECRET@push-par-clevercloud-customers.services.clever-cloud.com/app_264ddab9-51db-4d67-bce6-bce873520b60.git
            git push -u clever master
workflows:
    build_and_deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
